import os
import re
from typing import List, Tuple, Dict, Any
from src_v3.core.models import IRNode, IREdge, FileNode, SymbolNode, ImportEdge, CallEdge
from src_v3.providers.parser.base import ParserProvider

GENERATED_SIGNATURES = [
    r"generated by",
    r"do not edit",
    r"automatically generated",
    r"auto-generated",
    r"created by.*class generator"
]

def is_file_generated(content: str) -> bool:
    """
    Checks if a file appears to be auto-generated.
    """
    first_few_lines = "\n".join(content.splitlines()[:50]).lower()
    for sig in GENERATED_SIGNATURES:
        if re.search(sig, first_few_lines):
            return True
    return False

def calculate_code_density(content: str) -> float:
    """
    Calculates code density as the ratio of non-empty, non-comment lines to total lines.
    """
    lines = content.splitlines()
    if not lines:
        return 0.0
        
    code_lines = 0
    total_lines = len(lines)
    
    for line in lines:
        line_strip = line.strip()
        if not line_strip:
            continue
        # Skip comments (python, js, go, c style)
        if line_strip.startswith("#") or line_strip.startswith("//") or line_strip.startswith("/*") or line_strip.startswith("*"):
            continue
        code_lines += 1
        
    return code_lines / total_lines

def normalize_node_id(text: str) -> str:
    """
    Normalizes a path or identifier to be used safely as an IR node ID.
    """
    return re.sub(r'[^a-zA-Z0-9_\-\.]', '_', text)

def build_file_ir(file_path: str, repo_path: str, lang: str, provider: ParserProvider, query_pack: Dict[str, Any]) -> Tuple[List[IRNode], List[IREdge]]:
    """
    Parses a single file and builds unified FileNode, SymbolNode and ImportEdge objects.
    """
    rel_path = os.path.relpath(file_path, repo_path)
    
    # Read content for density and generated checks
    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
        
    is_gen = is_file_generated(content)
    density = calculate_code_density(content)
    total_lines = len(content.splitlines())
    
    # 1. Create File Node
    file_node_id = f"file_{normalize_node_id(rel_path)}"
    file_node = FileNode(
        node_id=file_node_id,
        kind="file",
        lang=lang,
        file=rel_path,
        symbol="",
        span={"start": 1, "end": max(1, total_lines)},
        attributes={
            "code_density": density,
            "is_generated": is_gen
        }
    )
    
    nodes = [file_node]
    edges = []
    
    # Parse file using provider
    try:
        tree = provider.parse_file(file_path, lang)
        
        # 2. Extract symbols
        symbols_data = provider.extract_symbols(tree, query_pack)
        for sym in symbols_data:
            start_line = sym["span"]["start"]
            end_line = sym["span"]["end"]
            name = sym["symbol"]
            kind = sym["kind"]
            
            sym_node_id = f"sym_{normalize_node_id(rel_path)}_{normalize_node_id(name)}_{start_line}_{end_line}"
            
            sym_attributes = sym.get("attributes", {}).copy()
            sym_attributes.update({
                "is_generated": is_gen,
                "symbol_kind": kind
            })
            
            sym_node = SymbolNode(
                node_id=sym_node_id,
                kind="symbol",
                lang=lang,
                file=rel_path,
                symbol=name,
                span=sym["span"],
                attributes=sym_attributes
            )
            nodes.append(sym_node)
            
            # Create a containment edge (file contains symbol)
            edges.append(IREdge(
                edge_id=f"contain_{file_node_id}_{sym_node_id}",
                kind="contain",
                src_node_id=file_node_id,
                dst_node_id=sym_node_id,
                confidence=1.0,
                resolution_kind="exact",
                provider_trace=[provider.provider_name]
            ))
            
        # 3. Extract imports
        imports_data = provider.extract_imports(tree, query_pack)
        for idx, imp in enumerate(imports_data):
            imp_name = imp["import_name"]
            source = imp["source"]
            
            # Normalization of import target node ID
            import_target_id = f"import_{normalize_node_id(source)}"
            
            edges.append(ImportEdge(
                edge_id=f"import_{file_node_id}_{idx}",
                kind="import",
                src_node_id=file_node_id,
                dst_node_id=import_target_id,
                confidence=1.0,
                resolution_kind="fuzzy",
                provider_trace=[provider.provider_name]
            ))
            
    except Exception as e:
        # If parsing fails, we still keep the FileNode but log/trace the error in attributes
        file_node.attributes["parse_error"] = str(e)
        
    return nodes, edges
