import os
import re
from typing import List, Tuple, Dict, Any
from src_v3.core.models import (
    IRNode, IREdge, FileNode, SymbolNode, ImportEdge, CallEdge,
    TypeHint, ResourceAccess, GuardCheck, StateTransition, Entrypoint
)
from src_v3.providers.parser.base import ParserProvider

GENERATED_SIGNATURES = [
    r"generated by",
    r"do not edit",
    r"automatically generated",
    r"auto-generated",
    r"created by.*class generator"
]

def is_file_generated(content: str) -> bool:
    """
    Checks if a file appears to be auto-generated.
    """
    first_few_lines = "\n".join(content.splitlines()[:50]).lower()
    for sig in GENERATED_SIGNATURES:
        if re.search(sig, first_few_lines):
            return True
    return False

def calculate_code_density(content: str) -> float:
    """
    Calculates code density as the ratio of non-empty, non-comment lines to total lines.
    """
    lines = content.splitlines()
    if not lines:
        return 0.0
        
    code_lines = 0
    total_lines = len(lines)
    
    for line in lines:
        line_strip = line.strip()
        if not line_strip:
            continue
        # Skip comments (python, js, go, c style)
        if line_strip.startswith("#") or line_strip.startswith("//") or line_strip.startswith("/*") or line_strip.startswith("*"):
            continue
        code_lines += 1
        
    return code_lines / total_lines

def normalize_node_id(text: str) -> str:
    """
    Normalizes a path or identifier to be used safely as an IR node ID.
    """
    return re.sub(r'[^a-zA-Z0-9_\-\.]', '_', text)

def _record_extraction_failure(file_node: IRNode, stage: str, exc: Exception) -> None:
    """
    Keep parser sub-stage failures visible on the file node instead of silently
    losing partial IR. V3 permits transparent fallback/partial parse, but the
    degradation must be inspectable downstream through IR/manifest/reporting.
    """
    failures = file_node.attributes.setdefault("extraction_failures", [])
    failures.append({
        "stage": stage,
        "error_type": exc.__class__.__name__,
        "message": str(exc)
    })
    reasons = file_node.attributes.setdefault("degradation_reasons", [])
    reason = f"parser extraction stage '{stage}' failed: {exc.__class__.__name__}: {exc}"
    if reason not in reasons:
        reasons.append(reason)
    file_node.attributes["parse_partial"] = True

def build_file_ir(file_path: str, repo_path: str, lang: str, provider: ParserProvider, query_pack: Dict[str, Any]) -> Tuple[List[IRNode], List[IREdge]]:
    """
    Parses a single file and builds unified FileNode, SymbolNode, custom IRNodes and IREdges.
    """
    rel_path = os.path.relpath(file_path, repo_path)
    
    # Read content for density and generated checks
    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
        
    is_gen = is_file_generated(content)
    density = calculate_code_density(content)
    total_lines = len(content.splitlines())
    
    # 1. Create File Node
    file_node_id = f"file_{normalize_node_id(rel_path)}"
    file_node = FileNode(
        node_id=file_node_id,
        kind="file",
        lang=lang,
        file=rel_path,
        symbol="",
        span={"start": 1, "end": max(1, total_lines)},
        attributes={
            "code_density": density,
            "is_generated": is_gen
        }
    )
    
    nodes = [file_node]
    edges = []
    
    # Parse file using provider
    try:
        tree = provider.parse_file(file_path, lang)
        # Store parsing mode and check if fallback was used
        parse_mode = tree.get("mode") if isinstance(tree, dict) else "unknown"
        file_node.attributes["parse_mode"] = parse_mode
        if isinstance(tree, dict):
            for attr_name in ["parser_runtime", "is_real_wasm_runtime", "degradation_reason"]:
                if attr_name in tree:
                    file_node.attributes[attr_name] = tree[attr_name]
        
        # 2. Extract symbols
        symbols_data = provider.extract_symbols(tree, query_pack)
        for sym in symbols_data:
            start_line = sym["span"]["start"]
            end_line = sym["span"]["end"]
            name = sym["symbol"]
            kind = sym["kind"]
            
            sym_node_id = f"sym_{normalize_node_id(rel_path)}_{normalize_node_id(name)}_{start_line}_{end_line}"
            
            sym_attributes = sym.get("attributes", {}).copy()
            sym_attributes.update({
                "is_generated": is_gen,
                "symbol_kind": kind
            })
            
            sym_node = SymbolNode(
                node_id=sym_node_id,
                kind="symbol",
                lang=lang,
                file=rel_path,
                symbol=name,
                span=sym["span"],
                attributes=sym_attributes
            )
            nodes.append(sym_node)
            
            # Create a containment edge (file contains symbol)
            edges.append(IREdge(
                edge_id=f"contain_{file_node_id}_{sym_node_id}",
                kind="contain",
                src_node_id=file_node_id,
                dst_node_id=sym_node_id,
                confidence=1.0,
                resolution_kind="exact",
                provider_trace=[provider.provider_name]
            ))
            
        # 3. Extract imports
        imports_data = provider.extract_imports(tree, query_pack)
        for idx, imp in enumerate(imports_data):
            imp_name = imp["import_name"]
            source = imp["source"]
            
            # Normalization of import target node ID
            import_target_id = f"import_{normalize_node_id(source)}"
            
            edges.append(ImportEdge(
                edge_id=f"import_{file_node_id}_{idx}",
                kind="import",
                src_node_id=file_node_id,
                dst_node_id=import_target_id,
                confidence=1.0,
                resolution_kind="fuzzy",
                provider_trace=[provider.provider_name]
            ))
            
        # 4. Extract Calls
        try:
            calls_data = provider.extract_calls(tree, query_pack)
            for idx, call in enumerate(calls_data):
                callee_name = call["callee"]
                caller_name = call["caller"]
                start_line = call["span"]["start"]
                
                # Find caller node id if caller_name is given
                caller_node_id = file_node_id
                if caller_name:
                    for n in nodes:
                        if n.kind == "symbol" and n.symbol == caller_name:
                            caller_node_id = n.node_id
                            break
                else:
                    # Enclosing symbol heuristic by span
                    for n in nodes:
                        if n.kind == "symbol" and n.span["start"] <= start_line <= n.span["end"]:
                            caller_node_id = n.node_id
                            break
                            
                callee_target_id = f"sym_global_{normalize_node_id(callee_name)}"
                for n in nodes:
                    if n.kind == "symbol" and n.symbol == callee_name:
                        callee_target_id = n.node_id
                        break
                        
                edges.append(CallEdge(
                    edge_id=f"call_{caller_node_id}_{normalize_node_id(callee_name)}_{start_line}_{idx}",
                    kind="call",
                    src_node_id=caller_node_id,
                    dst_node_id=callee_target_id,
                    confidence=0.9,
                    resolution_kind="exact" if callee_target_id != f"sym_global_{normalize_node_id(callee_name)}" else "fuzzy",
                    provider_trace=[provider.provider_name]
                ))
        except Exception as exc:
            _record_extraction_failure(file_node, "calls", exc)

        # 5. Extract TypeHints
        try:
            type_hints_data = provider.extract_type_hints(tree, query_pack)
            for idx, th in enumerate(type_hints_data):
                th_name = th["symbol"]
                start = th["span"]["start"]
                th_node_id = f"hint_{normalize_node_id(rel_path)}_{normalize_node_id(th_name)}_{start}_{idx}"
                th_node = TypeHint(
                    node_id=th_node_id,
                    kind="type_hint",
                    lang=lang,
                    file=rel_path,
                    symbol=th_name,
                    span=th["span"],
                    attributes={"is_generated": is_gen, "type_name": th_name}
                )
                nodes.append(th_node)
                edges.append(IREdge(
                    edge_id=f"contain_{file_node_id}_{th_node_id}",
                    kind="contain",
                    src_node_id=file_node_id,
                    dst_node_id=th_node_id,
                    confidence=1.0,
                    resolution_kind="exact",
                    provider_trace=[provider.provider_name]
                ))
        except Exception as exc:
            _record_extraction_failure(file_node, "type_hints", exc)

        # 6. Extract Resources
        try:
            resources_data = provider.extract_resources(tree, query_pack)
            for idx, res in enumerate(resources_data):
                res_name = res["symbol"]
                start = res["span"]["start"]
                res_node_id = f"res_{normalize_node_id(rel_path)}_{normalize_node_id(res_name)}_{start}_{idx}"
                res_node = ResourceAccess(
                    node_id=res_node_id,
                    kind="resource_access",
                    lang=lang,
                    file=rel_path,
                    symbol=res_name,
                    span=res["span"],
                    attributes={"is_generated": is_gen, "resource_kind": res_name}
                )
                nodes.append(res_node)
                edges.append(IREdge(
                    edge_id=f"contain_{file_node_id}_{res_node_id}",
                    kind="contain",
                    src_node_id=file_node_id,
                    dst_node_id=res_node_id,
                    confidence=1.0,
                    resolution_kind="exact",
                    provider_trace=[provider.provider_name]
                ))
        except Exception as exc:
            _record_extraction_failure(file_node, "resources", exc)

        # 7. Extract Guards
        try:
            guards_data = provider.extract_guards(tree, query_pack)
            for idx, gd in enumerate(guards_data):
                gd_name = gd["symbol"]
                start = gd["span"]["start"]
                gd_node_id = f"guard_{normalize_node_id(rel_path)}_{normalize_node_id(gd_name)}_{start}_{idx}"
                gd_node = GuardCheck(
                    node_id=gd_node_id,
                    kind="guard_check",
                    lang=lang,
                    file=rel_path,
                    symbol=gd_name,
                    span=gd["span"],
                    attributes={"is_generated": is_gen, "guard_type": gd_name}
                )
                nodes.append(gd_node)
                edges.append(IREdge(
                    edge_id=f"contain_{file_node_id}_{gd_node_id}",
                    kind="contain",
                    src_node_id=file_node_id,
                    dst_node_id=gd_node_id,
                    confidence=1.0,
                    resolution_kind="exact",
                    provider_trace=[provider.provider_name]
                ))
        except Exception as exc:
            _record_extraction_failure(file_node, "guards", exc)

        # 8. Extract States
        try:
            states_data = provider.extract_states(tree, query_pack)
            for idx, st in enumerate(states_data):
                st_name = st["symbol"]
                start = st["span"]["start"]
                st_node_id = f"state_{normalize_node_id(rel_path)}_{normalize_node_id(st_name)}_{start}_{idx}"
                st_node = StateTransition(
                    node_id=st_node_id,
                    kind="state_transition",
                    lang=lang,
                    file=rel_path,
                    symbol=st_name,
                    span=st["span"],
                    attributes={"is_generated": is_gen, "state_action": st_name}
                )
                nodes.append(st_node)
                edges.append(IREdge(
                    edge_id=f"contain_{file_node_id}_{st_node_id}",
                    kind="contain",
                    src_node_id=file_node_id,
                    dst_node_id=st_node_id,
                    confidence=1.0,
                    resolution_kind="exact",
                    provider_trace=[provider.provider_name]
                ))
        except Exception as exc:
            _record_extraction_failure(file_node, "states", exc)

        # 9. Extract Entrypoints
        try:
            entrypoints_data = provider.extract_entrypoints(tree, query_pack)
            for idx, ep in enumerate(entrypoints_data):
                ep_name = ep["symbol"]
                start = ep["span"]["start"]
                ep_node_id = f"entry_{normalize_node_id(rel_path)}_{normalize_node_id(ep_name)}_{start}_{idx}"
                ep_node = Entrypoint(
                    node_id=ep_node_id,
                    kind="entrypoint",
                    lang=lang,
                    file=rel_path,
                    symbol=ep_name,
                    span=ep["span"],
                    attributes={"is_generated": is_gen, "entrypoint_type": "web"}
                )
                nodes.append(ep_node)
                edges.append(IREdge(
                    edge_id=f"contain_{file_node_id}_{ep_node_id}",
                    kind="contain",
                    src_node_id=file_node_id,
                    dst_node_id=ep_node_id,
                    confidence=1.0,
                    resolution_kind="exact",
                    provider_trace=[provider.provider_name]
                ))
        except Exception as exc:
            _record_extraction_failure(file_node, "entrypoints", exc)

    except Exception as e:
        # If parsing fails, we still keep the FileNode but log/trace the error in attributes
        file_node.attributes["parse_error"] = str(e)
        file_node.attributes["parse_mode"] = "failed"
        file_node.attributes["degradation_reasons"] = [
            f"parser failed: {e.__class__.__name__}: {e}"
        ]
        
    return nodes, edges
